---
- name: add Debian Wheezy workaround
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "wheezy")

- name: STRETCH BROKEN PACKAGE - Push missing dependencies
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "stretch")
    or (ansible_distribution_release == "buster")
  with_items:
    - libmariadb2_2.3.2-2_amd64.deb
    - libssl1.0.0_1.0.1t-1+deb8u11_amd64.deb

- name: STRETCH BROKEN PACKAGE - Install missing dependencies
  apt:
    deb: "/tmp/{{ item }}"
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "stretch")
    or (ansible_distribution_release == "buster")
  with_items:
    - libmariadb2_2.3.2-2_amd64.deb
    - libssl1.0.0_1.0.1t-1+deb8u11_amd64.deb

- name: STRETCH BROKEN PACKAGE - Install dependencies
  apt:
    name:
      - libmariadb2
      - libpcre2-8-0
      - expect
    state: present
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "stretch")
    or (ansible_distribution_release == "buster")

- name: STRETCH BROKEN PACKAGE - Delete tmp debian package
  file:
    path: "/tmp/{{ item }}"
    state: absent
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "stretch")
    or (ansible_distribution_release == "buster")
  with_items:
    - libmariadb2_2.3.2-2_amd64.deb
    - libssl1.0.0_1.0.1t-1+deb8u11_amd64.deb

- name: Install ossec package
  apt:
    name: ossec-hids-server
    state: present

- name: push configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: ossec
    group: ossec
    mode: 0640
  with_items:
    - src: "var/ossec/etc/ossec.conf.j2"
      dest: "/var/ossec/etc/ossec.conf"
    - src: "var/ossec/etc/decoder.xml.j2"
      dest: "/var/ossec/etc/decoder.xml"
    - src: "var/ossec/rules/local_rules.xml.j2"
      dest: "/var/ossec/rules/local_rules.xml"
  notify:
    - start ossec service

- meta: flush_handlers
