---
- name: Install ossec package
  apt:
    name: ossec-hids-server
    state: latest

- name: push ossec.conf
  template:
    src: "var/ossec/etc/ossec.conf.j2"
    dest: "/var/ossec/etc/ossec.conf"
    owner: ossec
    group: ossec
    mode: 0640

- name: start ossec service
  service:
    name: ossec
    state: started
