---
- name: add Debian Wheezy workaround
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "wheezy")

- name: Install ossec package
  apt:
    name: ossec-hids-server
    state: latest

- name: push configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: ossec
    group: ossec
    mode: 0640
  with_items:
    - src: "var/ossec/etc/ossec.conf.j2"
      dest: "/var/ossec/etc/ossec.conf"
    - src: "var/ossec/etc/decoder.xml.j2"
      dest: "/var/ossec/etc/decoder.xml"
    - src: "var/ossec/rules/local_rules.xml.j2"
      dest: "/var/ossec/rules/local_rules.xml"
  register: ossec_conf

- name: start ossec service
  service:
    name: ossec
    state: restarted
  when: ossec_conf.changed
